config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  root 'welcome#index'
  get 'about' => 'welcome#about'

  resources :users
  resources :potential_appointments
  resources :carts
  resources :orders
  resources :comments
  resources :password_resets, only: [:new, :create, :edit, :update]

  patch 'users/:id' => 'users#verify', as: 'users_verify'
  get 'users/:id/email_confirm' => 'users#email_confirm', as: 'email_confirm_user'

  get 'FinNetwork' => 'advisors#index', as: 'advisors'
  get 'FinNetwork/new' => 'advisors#new', as: 'advisor_new'
  post 'FinNetwork' => 'advisors#create'
  get 'FinNetwork/:id' => 'advisors#show', as: 'advisor'
  get 'FinNetwork/:id/edit' => 'advisors#edit', as: 'edit_advisor'
  patch 'FinNetwork/:id' => 'advisors#update'
  delete 'FinNetwork/:id' => 'advisors#destroy'
  patch 'FinNetwork/:id/activate' => 'advisors#activate', as: 'activate_network'
  patch 'FinNetwork/:id/de_activate' => 'advisors#de_activate', as: 'de_activate_network'

  get 'network_members' => 'admins#index'
  get 'admin/login' => 'admins#new'
  post 'admin_login' => 'admins#create'
  delete 'admin_logout' => 'admins#destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :advisors do
    resources :previous_companies
  end

  resources :account_activations, only: [:edit]

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  belongs_to :category, :dependent => :destroy
  has_many :potential_appointments
  has_many :previous_companies

  validates :email, :presence => true
  validates :email, uniqueness: true


  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_confirmation_of :email, :message => "Should match confirmation"
  validates_presence_of :email_confirmation

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://prepgenie.ie/gamsat/wp-content/uploads/2015/08/default-avatar_man.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]


  attr_accessor :activation_token
  before_create :create_activation_digest


  has_secure_password



def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while Advisor.exists?(column => self[column])
end

def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  self.email_confirmation = self.email
  save!
  AdvisorMailer.password_reset(self).deliver
end

def authenticated?(attribute, token)
  digest = send("#{attribute}_digest")
  return false if digest.nil?
  BCrypt::Password.new(digest).is_password?(token)
end

def Advisor.new_token
  SecureRandom.urlsafe_base64
end

def Advisor.digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  BCrypt::Engine.cost
  BCrypt::Password.create(string, cost: cost)
end

private


def create_activation_digest
  self.activation_token  = Advisor.new_token
  self.activation_digest = Advisor.digest(activation_token)
end


end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController

  before_action :correct_advisor, only:[:edit, :update]


  def index
    if params[:filter]
      if params[:filter][:category]
        advisors_by_category = params[:filter][:category].map do |category|
          Category.find_by(name: category).advisors.where("account_activated = ? AND publish = ?", true, true)
        end
        advisors_by_category.flatten!
      else
        advisors_by_category = Advisor.where("account_activated = ? AND publish = ?", true, true)
      end
      if params[:filter][:location]
        advisors_by_location = params[:filter][:location].map do |location|
          Advisor.where("account_activated = ? AND publish = ? AND location = ?", true, true, location)
        end
        advisors_by_location.flatten!.uniq!
      else
        advisors_by_location = Advisor.where("account_activated = ? AND publish = ?", true, true)
      end
      if params[:filter][:years_of_experience]
        advisors_by_years = params[:filter][:years_of_experience].map do |range|
          Advisor.where("account_activated = ? AND publish = ? AND years_of_experience = ?", true, true, range)
        end
        advisors_by_years.flatten!.uniq!
      else
        advisors_by_years = Advisor.where("account_activated = ? AND publish = ?", true, true)
      end
      @advisors = advisors_by_category & advisors_by_location & advisors_by_years
      flash[:message] = "Search Results"
    else
      @advisors = Advisor.where("account_activated = ? AND publish = ?", true, true)
    end
  end



  def new
    @advisor = Advisor.new
  end

  def create
    advisor = Advisor.new(advisor_params)
    if advisor.save && advisor.valid?
      session[:user_or_advisor_id] = advisor.id
      session[:class_type] = advisor.class.name
      AdvisorMailer.email_verification(advisor).deliver_now
      flash[:thank_you] = "Thank you!"
      redirect_to edit_advisor_path(advisor)
    else
      flash[:errors] = advisor.errors.full_messages
      redirect_to advisor_new_path
    end
  end

  def show
    if logged_in? || admin_logged_in?
      advisor = Advisor.find_by(id: params[:id])
      if (advisor.publish == true && advisor.account_activated == true) || (current_advisor == advisor) || admin_logged_in?
        @advisor = advisor
        advisor_appointments = @advisor.potential_appointments
        @previous_companies = @advisor.previous_companies.order("id ASC")
        @advisor_appointments = advisor_appointments.sort_by { |appointment| appointment.start_time.strftime("%b,%d") }
        @potential_appointment = PotentialAppointment.new
      else
        render :inactivated_advisor
      end
    else
      flash[:acces_denied] = "Please Login or Signup to view this page"
      redirect_to login_path
    end
  end

  def edit
    @advisor = Advisor.find_by(id: params[:id])
    @previous_companies = @advisor.previous_companies.order("id ASC")
    @previous_company = PreviousCompany.new
  end

  def update
    advisor = Advisor.find_by(id: params[:id])
    if params[:other_expertise]
      other_categories = []
      params[:other_expertise].each do |category_name|
        other_categories << category_name
      end
      advisor.other_expertise = other_categories.join(", ")
    end
    advisor.category = Category.find_or_create_by(name: params[:category][:name])
    advisor.update(advisor_params)
    if params[:category][:name] == "Resume & Interview Preparation"
      advisor.student_price = 50
      advisor.regular_price = 60
    else
      if advisor.years_of_experience == '< 5 years'
        advisor.student_price = 30
        advisor.regular_price = 40
      elsif advisor.years_of_experience == '5 - 15 years'
        advisor.student_price = 30
        advisor.regular_price = 40
      else
        advisor.student_price = 50
        advisor.regular_price = 60
      end
    end
    if advisor.save
      redirect_to advisor_path(advisor)
    else
      flash[:error] = advisor.errors.full_messages
      redirect_to edit_advisor_path(current_advisor)
    end
  end

  def activate
    advisor = Advisor.find_by(id: params[:id])
    advisor.update(account_activated: true, email_confirmation: advisor.email)
    redirect_to network_members_path
  end

   def de_activate
    advisor = Advisor.find_by(id: params[:id])
    advisor.update(account_activated: false, email_confirmation: advisor.email)
    redirect_to network_members_path
  end


  def destroy
    advisor = Advisor.find_by(id: params[:id])
    advisor.destroy
    redirect_to network_members_path
  end

  private

  def advisor_params
    params.require(:advisor).permit(:email, :email_confirmation, :password,:password_confirmation,  :firstname, :lastname, :avatar, :alternative_email, :current_title, :job_description, :charity, :charity_url, :languages, :publish, :location, :company, :years_of_experience, :other_companies, :education, :certifications, :interesting_facts, :account_activated, :general_company, :other_expertise, :phone_number)
  end


  def correct_advisor
    @advisor = Advisor.find(params[:id])
    redirect_to(root_url) unless @advisor == current_advisor || session[:class_type] == "Admin"
  end

end

app/views/advisors/_results_index.html.erb
<% if @advisors == [] || @advisors.nil? %>
<p id="no-matches-message">Sorry, there were no professionals that matched your search!</p>
<% else %>
<div id="search-results-flash"><p><%= flash[:message] %></p></div>
<% @advisors.each do |advisor| %>

<div class="small-12 medium-12 large-6 columns" id="advisor-list-holder">
  <div class="row" id="advisor-index-panel">
    <div class="small-6 medium-4 large-4 columns">
      <div class="row" id="advisor-index-avatar">
        <%= image_tag advisor.avatar.url(:medium) %>
      </div>
    </div>
    <div class="small-12 medium-8 large-8 columns">
      <div class="row">
        <div class="small-8 medium-8 large-8 columns">
          <p class="index-advisor-name"><%= advisor.firstname %></p>
          <p class="index-advisor-title-location"><%= advisor.current_title %> | <%= advisor.location %></p>
          <p class="index-advisor-years-of-experience"><%= advisor.years_of_experience %></p>
        </div>
        <div class="small-4 medium-4 large-4 columns" id="advisor-index-price">
          <% if logged_in? %>
          <% if current_user && current_user.student == true %>
          <p class="advisor-price-number">$<%= advisor.student_price %></p>
          <p class="advisor-price-session">Consultation</p>
          <% else %>
          <p class="advisor-price-number">$<%= advisor.regular_price %></p>
          <p class="advisor-price-session">Consultation</p>
          <% end %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 medium-12 large-12 columns" id="index-advisor-services">
          <p class="advisors-index-categories"><%= advisor.category.name %></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-12 large-12 columns">
        <% if logged_in? || admin_logged_in? %>
          <%= link_to "More Details", advisor_path(advisor), class: "book-appt-btn" %>
          <% else %>
          <%= link_to "More Details", advisor_path(advisor), class: "book-appt-btn", id: "must-login" %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

<% end %>

app/views/advisors/inactivated_advisor.html.erb
<div id="inactive-container">
  <h2>This is an inactive account</h2>
</div>

app/views/advisors/new.html.erb
<div class="row" id="ribbon-header">
</div>


  <div class="row">
    <div class=" small-12 small-centered medium-11 medium-centered large-5 large-centered columns">
      <div class="signup-panel">
        <div class="row">
          <h2 id="signup_header">HOB NOB Professional Network</h2>
          <p id="signup_advisor">Signup to Create Your Profile</p>
        </div>

          <% if flash[:errors] %>
          <% flash[:errors].each do |msg| %>
          <div class="row">
            <div class="small-12 medium-11 medium-centered large-10 large-centered columns">
              <div data-alert class="alert-box alert radius">
                <%= msg %>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>


        <%= form_for @advisor do |f| %>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.text_field :firstname, placeholder: "First Name" %>
          </div>
        </div>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.text_field :lastname, placeholder: "Last Name" %>
          </div>
        </div>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.text_field :email, placeholder: "Email" %>
          </div>
        </div>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.text_field :email_confirmation, placeholder: "Confirm Email" %>
          </div>
        </div>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.password_field :password, placeholder: "Password" %>
          </div>
        </div>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
          </div>
        </div>
        <div class="row">
          <div class="large-10 large-centered small-11 small-centered columns">
            <%= f.submit "Register", :class => "full-button" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/advisors/show.html.erb
<div class="row" id="ribbon-header">
</div>


<div class="row" id="advisor-profile-container">
  <div class="small-12 medium-12 large-12 columns" id='profile-panel'>
    <div id="advisor-profile-image">
      <div id="advisor-index-avatar">
        <%= image_tag @advisor.avatar.url(:medium) %>
      </div>
    </div>
    <div class="row" id="advisor-profile-bio">
      <p id="advisor-name-profile-page"><%= @advisor.firstname %></p>
      <p id="advisor-title-profile-page"><%= @advisor.current_title %> | <%= @advisor.location %></p>
      <% if !@advisor.category.nil? %>
      <p id="advisor-category-profile-page"><%= @advisor.category.name %></p>
      <% end %>
    </div>
    <div class="flash-holder">
      <% if current_advisor == @advisor || session[:class_type] == "Admin" %>
      <% if @advisor.publish == false %>
      <p id="publish-profile-text">*Your profile is currently set to private. To set it to public, click below and please check PUBLISH</p>
      <% end %>
      <div id="advisor-edit-btn">
        <%= link_to "Edit Profile", edit_advisor_path(@advisor), class: "button" %>
      </div>
      <% end %>
      <p id='flash_add_cart'><%=flash[:added_to_cart] %></p>
      <p id='flash_already_cart'><%=flash[:already_in_cart] %></p>
    </div>

  </div>



  <div class="small-12 medium-12 large-12 columns" id="advisor-bio-panel">
    <div class="row">
      <div class="small-12 medium-12 large-6 columns" id="advisor-bio-box">
        <p class="advisor-profile-header">Details</p>

        <div id="advisor-about">
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class='profile-subheader'>Current Company</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.general_company %></p>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.job_description %></p>
            </div>
          </div>
          <div class="spacer">
          </div>
          <% if @previous_companies != [] %>
          <% @previous_companies.each do |company| %>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <% if company == @previous_companies.first %>
              <p class='profile-subheader'>Previous Company(s)</p>
              <% end %>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info">
                <%= company.name %>
              </p>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= company.job_title %></p>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= company.roles %></p>
            </div>
          </div>
          <div class="spacer">
          </div>

          <% end %>
          <% end %>

          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class='profile-subheader'>Education</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.education %></p>
            </div>
          </div>

          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class='profile-subheader'>Years of Experience</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.years_of_experience %></p>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class="profile-subheader">Finance Certifications</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.certifications %></p>
            </div>
          </div>

          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class='profile-subheader'>Language(s)</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.languages %></p>
            </div>
          </div>
          <div class="spacer">
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class='profile-subheader'>Charity of Choice</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.charity %></p>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.charity_url %></p>
            </div>
          </div>
          <div class="spacer">
          </div>


          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class='profile-subheader'>Other Areas of Expertise</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <% if !@advisor.other_expertise.nil? %>
              <% @advisor.other_expertise.split(",").each do |expertise| %>
              <p class="profile-info"><%= expertise %></p>
              <% end %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-4 large-4 columns">
              <p class="profile-subheader">Other Information</p>
            </div>
            <div class="small-12 medium-8 large-8 columns">
              <p class="profile-info"><%= @advisor.interesting_facts %></p>
            </div>
          </div>
        </div>
      </div>

      <% if (current_advisor == @advisor || session[:class_type] == "Admin") && !@advisor.category.nil? %>
      <div class='small-12 medium-12 large-6 columns' id="appointment-form">
        <p class="advisor-profile-header">Create Connect Date & Time</p>
        <%= form_for @potential_appointment do |f| %>
        <% if flash[:pick_date_or_enter_title] %>
        <div class="row">
          <div class="small-11 small-centered medium-10 medium-centered large-10 large-centered columns">
            <div data-alert class="alert-box alert radius">
              <%= flash[:pick_date_or_enter_title] %>
            </div>
          </div>
        </div>
        <% end %>

        <%= f.hidden_field :advisor_id, :value => @advisor.id %>

        <div class="row">
          <div class="small-11 small-centered medium-10 medium-centered large-10 large-centered columns">
            <%= f.label :title %>
             <% if !@advisor.category.nil? %>
              <p id="appointment-session">Session: <%= @advisor.category.name %></p>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="small-11 small-centered medium-10 medium-centered large-10 large-centered columns">
            <%= f.label :date %>
            <%= date_field(:appointment_date,"date") %>
          </div>
        </div>
        <div class="row">
          <div class="small-11 small-centered medium-10 medium-centered large-10 large-centered columns">
            <%= f.label :Start_Time %>
            <%= time_select 'potential_appointment', 'start_time', {ampm: true, :time_separator => "", minute_step: 15 }, class: "start_time" %>

            <%= f.label :Length %>

            <% if @advisor.category.name == "Resume & Interview Preparation" %>
            <p class="appt-length">1 Hour</p>
            <% else %>
            <p class="appt-length">30 Minutes</p>
            <% end %>


          </div>
        </div>
        <div class="row" id="calendar-button-div">
          <div class="small-11 small-centered medium-10 medium-centered large-10 large-centered columns">
            <%= f.submit "Create", :class => "full-button" %>
          </div>
        </div>
        <% end %>
      </div>
      <% else %>
      <div class='small-12 medium-12 large-6 columns' id="advisor-appointment-box">
        <p class="advisor-profile-header">Available Times</p>
        <div id="advisor-times">
          <% @advisor_appointments.each do |pot_appointment| %>

          <div class="row" id="appointment-time-box">

            <div class="small-6 medium-4 large-3 columns">

              <div class="row" id="appointment-date">
                <p class="appointment-day"><%= pot_appointment.start_time.strftime("%d") %></p>
                <p class="appointment-month"><%= pot_appointment.start_time.strftime("%b") %></p>
              </div>
            </div>
            <div class="small-12 medium-6 large-6 columns">
              <div class="row">
                <p class="appointment-time"><%= pot_appointment.start_time.strftime("%l:%M %p") %>
                  <%= pot_appointment.end_time.strftime("to %l:%M %p EST") %>
                </p>
                <p class='appointment_title'>Session: <%= pot_appointment.title %></p>
                <p class="appointment-full-date"><%= pot_appointment.start_time.strftime("%A, %B %d, %Y") %>
                </p>
              </div>
            </div>

            <% if logged_in? %>
            <div class="hide-for-small small-6 medium-2 large-3 columns" id="advisor-consultation-price-box">
              <p class="dollar-sign">$</p>
              <% if current_user && current_user.student == true %>
              <p class="advisor-consultation-price"><%= @advisor.student_price %></p>
              <p class="advisor-consultation-label">consultation</p>
              <% else %>
              <p class="advisor-consultation-price"><%= @advisor.regular_price %></p>
              <p class="advisor-consultation-label">consultation</p>
              <% end %>

            </div>
            <% end %>
            <% if !current_advisor %>
            <div class="small-12 medium-12 large-12 columns">

              <div class="row" id="available-times-right-btn">
               <%= form_for @advisor, url: cart_path, method: "patch" do |f| %>
               <%= f.hidden_field :appointment_id, :value => pot_appointment.id %>
               <% if pot_appointment.booked_status? == true %>
               <p id="appointment-status">Status:<span id='booked'> Booked</p>
               <% else %>
               <%= f.submit "Get Connected", class: "hide-for-small", :id => "add_to_cart_btn"%>
               <%= f.submit "Connect", class: "show-for-small", :id => "add_to_cart_btn_small"%>
               <% end %>
               <% end %>
             </div>
           </div>
           <% end %>
         </div>
         <% end %>
       </div>
     </div>

     <% end %>

   </div>

   <% if current_advisor == @advisor || session[:class_type] == "Admin" %>

   <div class="row">
    <div class="small-12 medium-12 large-12 columns" id="advisor-appointment-box">
      <p class="advisor-profile-header">Available Times</p>

      <div id="advisor-times">
        <% @advisor_appointments.each do |pot_appointment| %>

        <div class="row" id="appointment-time-box">

          <div class="small-12 medium-3 large-2 columns">

            <div class="row" id="appointment-date">
              <p class="appointment-day"><%= pot_appointment.start_time.strftime("%d") %></p>
              <p class="appointment-month"><%= pot_appointment.start_time.strftime("%b") %></p>
            </div>
          </div>
          <div class="small-12 medium-7 large-7 columns">
            <div class="row">
              <p class="appointment-time"><%= pot_appointment.start_time.strftime("%l:%M %p") %>
                <%= pot_appointment.end_time.strftime("to %l:%M %p EST") %>
              </p>
              <p class='appointment_title'>Session: <%= pot_appointment.title %></p>
              <p class="appointment-full-date"><%= pot_appointment.start_time.strftime("%A, %B %d, %Y") %>
              </p>
            </div>
          </div>
          <div class="small-12 medium-12 large-3 columns">

           <% if pot_appointment.advisor == current_advisor && session[:class_type] == current_advisor.class.name && pot_appointment.booked_status? == false || session[:class_type] == "Admin" && pot_appointment.booked_status? == false %>
           <div class="row">
            <div class="small-12 medium-12 large-12 columns" id="edit-appt-btn">
              <%= link_to "Edit",edit_potential_appointment_path(pot_appointment), class: "alternative-button" %>
            </div>
            <div class="small-12 medium-12 large-12 columns" id="edit-appt-btn">
              <%= link_to "Delete",{:controller => 'potential_appointments', :action => 'destroy', :potential_appointment => pot_appointment.id}, :method => :delete, class: "alternative-button" %>
            </div>
          </div>
          <% else %>
          <p id="appointment-status">Status:<span id='booked'> Booked</p>
          <% end %>
        </div>
      </div>



      <% end %>
    </div>
  </div>
</div>
<% end %>
</div>

</div>