config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  root 'welcome#index'
  get 'about' => 'welcome#about'

  resources :users
  resources :potential_appointments
  resources :carts
  resources :orders
  resources :comments
  resources :password_resets, only: [:new, :create, :edit, :update]

  patch 'users/:id' => 'users#verify', as: 'users_verify'
  get 'users/:id/email_confirm' => 'users#email_confirm', as: 'email_confirm_user'

  get 'FinNetwork' => 'advisors#index', as: 'advisors'
  get 'FinNetwork/new' => 'advisors#new', as: 'advisor_new'
  post 'FinNetwork' => 'advisors#create'
  get 'FinNetwork/:id' => 'advisors#show', as: 'advisor'
  get 'FinNetwork/:id/edit' => 'advisors#edit', as: 'edit_advisor'
  patch 'FinNetwork/:id' => 'advisors#update'
  delete 'FinNetwork/:id' => 'advisors#destroy'
  patch 'FinNetwork/:id/activate' => 'advisors#activate', as: 'activate_network'
  patch 'FinNetwork/:id/de_activate' => 'advisors#de_activate', as: 'de_activate_network'

  get 'network_members' => 'admins#index'
  get 'admin/login' => 'admins#new'
  post 'admin_login' => 'admins#create'
  delete 'admin_logout' => 'admins#destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :advisors do
    resources :previous_companies
  end

  resources :account_activations, only: [:edit]

end

app/views/layouts/_footer.html.erb
<div class="row">
</div>

<footer class="footer">

  <p class="slogan"><img id="nav_logo" src="/assets/hn_logo_small.png"/></p>

      <div class="links">
        <%= link_to "Home", root_path %>
        <p>  •  </p>
        <%= link_to "About", about_path %>
        <p>  •  </p>
        <%= link_to "Network", advisors_path %>
        <p>  •  </p>
        <%= link_to "The Network's Charities", " http://www.thepelikangroup.com/charities.html" , :target => "_blank" %>
      </div>

      <p class="copywrite">Pelikan Group Inc.</p>
</footer>

app/views/layouts/_header.html.erb
<div class='fixed' id="nav-bar-holder">
  <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

  <nav class="menu show-for-large-up ">
    <h1 class="name"><img id="nav_logo" src="/assets/hn_logo_med.png"/></h1>
    <ul class="inline-list">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li ><%= link_to "Network", advisors_path %></li>


      <li id='flash_pw_reset'><%=flash[:pw_reset] %></li>
      <li id='flash_pw_confirm'><%= flash[:pw_reset_confirm] %></li>
      <li id='flash_add_cart'><%= flash[:email_verified] %></li>
      <li id='flash_add_cart'><%= flash[:success] %></li>

    </ul>
    <ul class="inline-list account-action">
      <% if logged_in? %>

      <% if session[:class_type] == "User" %>
      <li><%= link_to "Profile",user_path(session[:user_or_advisor_id]) %></li>
      <% else %>
      <li><%= link_to "Profile", advisor_path(session[:user_or_advisor_id]) %></li>
      <% end %>
      <li><%= link_to "Logout", logout_path, method: :delete, id: "logout-link" %></li>
      <% elsif admin_logged_in? %>
      <li><%= link_to "Show Network", network_members_path %>
        <li><%= link_to "Logout", admin_logout_path, method: :delete, id: "logout-link" %></li>
        <% else %>
        <li><%= link_to "Login", login_path, id: "login-link" %></li>
        <li class=""><a class="signup" href="/users/new" data-reveal-id="myModal">Signup</a></li>
        <% end %>
      </ul>
    </nav>


    <nav class="menu show-for-medium-only">
      <h1 class="name"><img id="nav_logo" src="/assets/hn_logo_med.png"/></h1>
      <%= link_to "Menu", "#", class: "mobile-header-dropdown", id: "medium-header-dropdown" %>
    </nav>

    <nav class="menu show-for-small-only">
      <ul class="inline-list">
        <h1 class="name" id="mobile-header-logo"><img id="nav_logo" src="/assets/hn_logo_med.png"/></h1>
        <%= link_to "Menu", "#", class: "mobile-header-dropdown", id: "small-header-dropdown" %>
      </ul>
    </nav>

    <ul class="mobile-header-menu">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Network", advisors_path %></li>
      <% if logged_in? %>
      <% if session[:class_type] == "User" %>
      <li><%= link_to "Profile",user_path(session[:user_or_advisor_id]) %></li>
      <% else %>
      <li><%= link_to "Profile", advisor_path(session[:user_or_advisor_id]) %></li>
      <% end %>
      <li><%= link_to "Logout", logout_path, method: :delete, id: "logout-link" %></li>
      <% elsif admin_logged_in? %>
      <li><%= link_to "Show Network", network_members_path %></li>
      <li><%= link_to "Logout", admin_logout_path, method: :delete, id: "logout-link" %></li>
      <% else %>
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to "Signup", new_user_path %></li>
      <% end %>
    </ul>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Hobnob" %></title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>
</body>

</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>PDF</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= wicked_pdf_stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>